### ISSUE TITLE
Properties should inherit `additionalProperties` that is set on the builder

### ISSUE THREAD

**Issue by margani** [json-everything/json-everything#810] opened 2024-10-28 16:25 UTC
### Nuget Package

JsonSchema.Net

### Package Version

v7.2.3

### Operating System

None

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

Properties are not inheriting `additionalProperties` attribute.

### What did you expect?

When I set `additionalProperties: false` on the builder, I expect this attribute is `false` for all properties and sub properties:

```csharp
var schema = builder.FromType<T>().AdditionalProperties(false).Build();
```

### Please add test code or steps to reproduce the behavior.

Schema:

```json
{
  "additionalProperties": false,
  "type": "object",
  "properties": {
    "Prop1": {
      "type": "object",
      "properties": {
        "Prop11": {
          "type": "boolean"
        }
      }
    }
  }
}
```

Example JSON:
```json
{
    "Prop1": {
        "Prop12": "Silver",
        "Prop11": false
    }
}
```

Evaluation result:
```
{
  "valid": true,
  "details": [
    {
      "valid": true,
      "evaluationPath": "",
      "schemaLocation": "https://json-everything.net/258d53b103#",
      "instanceLocation": "",
      "annotations": {
        "properties": [
          "Prop1"
        ],
        "additionalProperties": []
      }
    },
    {
      "valid": true,
      "evaluationPath": "/properties/Prop1",
      "schemaLocation": "https://json-everything.net/258d53b103#/properties/Prop1",
      "instanceLocation": "/Prop1",
      "annotations": {
        "properties": [
          "Prop11"
        ]
      }
    },
    {
      "valid": true,
      "evaluationPath": "/properties/Prop1/properties/Prop11",
      "schemaLocation": "https://json-everything.net/258d53b103#/properties/Prop1/properties/Prop11",
      "instanceLocation": "/Prop1/Prop11"
    }
  ]
}
```

and when I change the schema to:

```json
{
  "additionalProperties": false,
  "type": "object",
  "properties": {
    "Prop1": {
      "type": "object",
      "properties": {
        "Prop11": {
          "type": "boolean"
        }
      },
      "additionalProperties": false
    }
  }
}
```

the result is:

```json
{
  "valid": false,
  "details": [
    {
      "valid": false,
      "evaluationPath": "",
      "schemaLocation": "https://json-everything.net/5aaf895f01#",
      "instanceLocation": ""
    },
    {
      "valid": false,
      "evaluationPath": "/properties/Prop1",
      "schemaLocation": "https://json-everything.net/5aaf895f01#/properties/Prop1",
      "instanceLocation": "/Prop1"
    },
    {
      "valid": true,
      "evaluationPath": "/properties/Prop1/properties/Prop11",
      "schemaLocation": "https://json-everything.net/5aaf895f01#/properties/Prop1/properties/Prop11",
      "instanceLocation": "/Prop1/Prop11"
    },
    {
      "valid": false,
      "evaluationPath": "/properties/Prop1/additionalProperties",
      "schemaLocation": "https://json-everything.net/5aaf895f01#/properties/Prop1/additionalProperties",
      "instanceLocation": "/Prop1/Prop12",
      "errors": {
        "": "All values fail against the false schema"
      }
    }
  ]
}
```

### Is there any other information you'd like to share regarding this bug?

Now I have to go to each class and add `[AdditionalProperties(false)]` so that it fails when there is an additional property in the JSON.

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment] 2024-10-28 17:23
Because this is a question about schema generation, can you list the C# code that you're using instead of the schemas, please?  You're taking about inheritance, and I can't see that in the schemas because inheritance a C# thing.

**Comment by margani** [comment] 2024-10-28 22:05
> Because this is a question about schema generation, can you list the C# code that you're using instead of the schemas, please? You're taking about inheritance, and I can't see that in the schemas because inheritance a C# thing.

Thank you.

By inheritance I didn't mean OO concept in programming languages. I meant the schema should apply this attribute to all sub properties.

The C# class for this generated schema is simple:

```csharp
public class BigClass
{
    public SmallClass Prop1 { get; set; }
}
public class SmallClass
{
    public SmallClass Prop11 { get; set; }
}
```

As you can see the other property `Prop12` doesn't exist, and I expect the validation to fail.

**Comment by gregsdennis** [comment] 2024-10-28 22:26
To be clear, are you saying that

```c#
[AdditionalProperties(false)]
public class BigClass
{
    public SmallClass Prop1 { get; set; }
}
public class SmallClass
{
    public bool Prop11 { get; set; }
}
```

should generate

```jsonc
{
  "additionalProperties": false,
  "type": "object",
  "properties": {
    "Prop1": {
      "type": "object",
      "properties": {
        "Prop11": {
          "type": "boolean"
        }
      },
      "additionalProperties": false  // <-- implicitly add this?
    }
  }
}
```

This violates type autonomy: each type should specify its own requirements.

If I were to run the generation for just `SmallClass`, it should produce the same schema as when running it for `BigClass`.  However, if `additionalProperties` cascades downward as you suggest, that wouldn't be the case.  `SmallClass` would produce

```jsonc
{
  "type": "object",
  "properties": {
    "Prop11": {
      "type": "boolean"
    }
  }
}
```

which is different from the schema produced when it's part of `BigClass`.  This is an unexpected behavior.

**Comment by margani** [comment] 2024-10-28 22:33
> To be clear, are you saying that
> 
> ```cs
> [AdditionalProperties(false)]
> public class BigClass
> {
>     public SmallClass Prop1 { get; set; }
> }
> public class SmallClass
> {
>     public bool Prop11 { get; set; }
> }
> ```
> 
> should generate
> 
> ```js
> {
>   "additionalProperties": false,
>   "type": "object",
>   "properties": {
>     "Prop1": {
>       "type": "object",
>       "properties": {
>         "Prop11": {
>           "type": "boolean"
>         }
>       },
>       "additionalProperties": false  // <-- implicitly add this?
>     }
>   }
> }
> ```
> 
> This violates type autonomy: each type should specify its own requirements.
> 
> If I were to run the generation for just `SmallClass`, it should produce the same schema as when running it as part of `BigClass`. However, if `additionalProperties` cascades downward as you suggest, that wouldn't be the case. `SmallClass` would produce
> 
> ```js
> {
>   "type": "object",
>   "properties": {
>     "Prop11": {
>       "type": "boolean"
>     }
>   }
> }
> ```
> 
> which is different from the schema produced when it's part of `BigClass`. This is an unexpected behavior.

Here is the code that says it's valid, which shouldn't be:

```csharp
using System.Text.Json;
using Json.Schema;
using Json.Schema.Generation;

namespace Test1;

public class Program
{
	public static void Main()
	{
		const string JsonToValidate = "{ \"Prop1\": { \"Prop11\": false, \"Prop12\": \"Something\" }  }";
		var builder = new JsonSchemaBuilder();
		var schema = builder.FromType<BigClass>().AdditionalProperties(false).Build();
		var jsonDocument = JsonDocument.Parse(JsonToValidate);
		var result = schema.Evaluate(jsonDocument);
		Console.WriteLine(new {
            IsValid = result.IsValid,
        });
	}
}

public class BigClass
{
    public SmallClass Prop1 { get; set; }
}
public class SmallClass
{
    public bool Prop11 { get; set; }
}
```

Here is the code that is not valid because I added `AdditionalProperties` attribute to SmallClass, although I have added that in `builder.FromType<BigClass>().AdditionalProperties(false).Build()`:

```csharp
using System.Text.Json;
using Json.Schema;
using Json.Schema.Generation;

namespace Test1;

public class Program
{
	public static void Main()
	{
		const string JsonToValidate = "{ \"Prop1\": { \"Prop11\": false, \"Prop12\": \"Something\" }  }";
		var builder = new JsonSchemaBuilder();
		var schema = builder.FromType<BigClass>().AdditionalProperties(false).Build();
		var jsonDocument = JsonDocument.Parse(JsonToValidate);
		var result = schema.Evaluate(jsonDocument);
		Console.WriteLine(new {
            IsValid = result.IsValid,
        });
	}
}

public class BigClass
{
    public SmallClass Prop1 { get; set; }
}
[AdditionalProperties(false)]
public class SmallClass
{
    public bool Prop11 { get; set; }
}
```

**Comment by margani** [comment] 2024-10-28 22:37
> To be clear, are you saying that
> 
> ```cs
> [AdditionalProperties(false)]
> public class BigClass
> {
>     public SmallClass Prop1 { get; set; }
> }
> public class SmallClass
> {
>     public bool Prop11 { get; set; }
> }
> ```
> 
> should generate
> 
> ```js
> {
>   "additionalProperties": false,
>   "type": "object",
>   "properties": {
>     "Prop1": {
>       "type": "object",
>       "properties": {
>         "Prop11": {
>           "type": "boolean"
>         }
>       },
>       "additionalProperties": false  // <-- implicitly add this?
>     }
>   }
> }
> ```
> 
> This violates type autonomy: each type should specify its own requirements.
> 
> If I were to run the generation for just `SmallClass`, it should produce the same schema as when running it as part of `BigClass`. However, if `additionalProperties` cascades downward as you suggest, that wouldn't be the case. `SmallClass` would produce
> 
> ```js
> {
>   "type": "object",
>   "properties": {
>     "Prop11": {
>       "type": "boolean"
>     }
>   }
> }
> ```
> 
> which is different from the schema produced when it's part of `BigClass`. This is an unexpected behavior.

I see what you mean now.

What of we add `"additionalProperties": false` to all sub properties in the schema when the builder has set it globally.

That means if you set it globally you need to enable it for the classes that you want, and if you don't set it, you need to disable it for the classes that you want.

At the moment, I have disabled it, but then I have to disable it for all of my classes too, then what's the point of having it set globally?

**Comment by gregsdennis** [comment] 2024-10-28 22:40
> when the builder has set it globally

What do you mean by this?  There's not a way to set anything globally.

**Comment by margani** [comment] 2024-10-28 22:52
> > when the builder has set it globally
> 
> What do you mean by this? There's not a way to set anything globally.

By globally setting I mean in:

```csharp
    builder.FromType<BigClass>().AdditionalProperties(false).Build()
```

**Comment by gregsdennis** [comment] 2024-10-29 00:14
I think you have a misunderstanding of the builder methods.  They don't add any global behaviors.  They add individual keywords to the local schema. 

The intent is to aid explicitly building a schema like you would in JSON.

Here's an example: https://github.com/json-everything/json-everything/blob/master/src%2FJsonSchema%2FMetaSchemas.Draft7.cs

**Comment by margani** [comment] 2024-10-29 08:50
> I think you have a misunderstanding of the builder methods. They don't add any global behaviors. They add individual keywords to the local schema.
> 
> The intent is to aid explicitly building a schema like you would in JSON.
> 
> Here's an example: https://github.com/json-everything/json-everything/blob/master/src%2FJsonSchema%2FMetaSchemas.Draft7.cs
> 
> You can also find the docs for this here: https://docs.json-everything.net/schema/basics/#schema-inlining

Are you saying for this I have to add the `[AdditionalProperties(false)]` to all the sub classes to achieve this?

By the way, before this library, I used [Json.NET Schema](https://www.newtonsoft.com/jsonschema), and with only doing the following, I could achieve that:

```csharp
JSchema schema = schemaGenerator.Generate(typeof(Person));
schema.AllowAdditionalProperties = false;
```

**Comment by margani** [comment] 2024-10-29 09:08
I just checked `NJsonSchema`, and it is doing the same as Newtonsoft.

**Comment by gregsdennis** [comment] 2024-10-29 09:09
> Are you saying for this I have to add the [AdditionalProperties(false)] to all the sub classes to achieve this?

Two things:

1. The `[AdditionalProperties()]` attribute and the `.AdditionalProperties()` builder extension are different but related.  The attribute is used for generating schemas from .Net types.  The extension is for using the builder to explicitly construct a schema.  They both add the `additionalProperties` keyword, but for different purposes.  If you're going to use generation, using the attributes shows intentionality in your code.
2. Yes, schemas and types are 1:1. You annotate each type based on how you want its schema generated.  If multiple types need a keyword, then each type will need the attribute.

> I used Json.NET Schema

This is a different library built ground-up based on nearly a decade of experience building Manatee.Json, this library's predecessor, and direct involvement with and co-authorship of the JSON Schema specification.  I took no inspiration from the Newtonsoft libs and have no intention of matching James' API.

**Comment by margani** [comment] 2024-10-29 09:22
> > Are you saying for this I have to add the [AdditionalProperties(false)] to all the sub classes to achieve this?
> 
> Two things:
> 
> 1. The `[AdditionalProperties()]` attribute and the `.AdditionalProperties()` builder extension are different but related.  The attribute is used for generating schemas from .Net types.  The extension is for using the builder to explicitly construct a schema.  They both add the `additionalProperties` keyword, but for different purposes.  If you're going to use generation, using the attributes shows intentionality in your code.
> 2. Yes, schemas and types are 1:1. You annotate each type based on how you want its schema generated.  If multiple types need a keyword, then each type will need the attribute.
> 
> > I used Json.NET Schema
> 
> This is a different library built ground-up based on nearly a decade of experience building Manatee.Json, this library's predecessor, and direct involvement with and co-authorship of the JSON Schema specification. I took no inspiration from the Newtonsoft libs and have no intention of matching James' API.

Based on [here](https://json-schema.org/draft/2020-12/draft-bhutton-json-schema-00#rfc.section.10.3.2.3) in JSON Schema specification it's up to the implementation to cascade this to the subclasses, which clearly in this library we decided no to.

Thank you.

**Comment by gregsdennis** [comment] 2024-10-29 09:40
That's not at all what that last paragraph says.  (The last paragraph is the only one that says anything about an implementation choice.)

The last paragraph of Core 10.3.2.3 is talking about how to determine which properties are covered by `additionalProperties` during evaluation of an instance.  It has nothing to do with generation of schemas, nor does anything in the JSON Schema specs.

That section states that `additionalProperties` looks at the annotations from `properties` and `patternProperties` (each of which are arrays of the property names they've evaluated) and applies its subschema to any property not listed in those annotations.

Another way to do this is for the implementation to look at the instance and figure out separately which properties would be evaluated by those two keywords, then apply `additionalProperties` to the rest.  The outcome is the same, which is why the spec allowed for it.

Code generation of any kind is out of scope for the specifications.

**Comment by margani** [comment] 2024-10-29 10:06
I managed to do this without adding `[AdditionalProperties(false)]` to all of my C# classes. Instead I added that to a base class which all the sub classes are inheriting from. And it works.

```csharp
[AdditionalProperties(false)]
public abstract class BaseClass { }
```

**Closed** 2024-10-29 17:07 UTC
Labels: bug, pkg:schema, not-a-bug

**Comment by epenelle-genetec** [comment] 2025-02-26 22:20
@margani  I had the same issue. A Refiner would allow you to get rid of that base class.

```csharp
// Define your Refiner and Intent
public class AdditionalPropertiesRefiner : ISchemaRefiner
{
    public bool ShouldRun(SchemaGenerationContextBase context)
    {
        bool isObject = context
            .Intents.OfType<TypeIntent>()
            .Any(t => t.Type == SchemaValueType.Object);
        // ⬇️ This is where the magic is. No need to inherit from the base class everywhere.
        bool isFromCurrentAssembly = context.Type.Assembly == Assembly.GetExecutingAssembly(); 
        return isObject && isFromCurrentAssembly;
    }

    public void Run(SchemaGenerationContextBase context) => context.Intents.Add(new AdditionalPropertiesIntent());
}

public class AdditionalPropertiesIntent() : ISchemaKeywordIntent
{
    public void Apply(JsonSchemaBuilder builder) => builder.AdditionalProperties(false);
}

// Then, to generate your schema : 
SchemaGeneratorConfiguration config = new()
{
    PropertyNameResolver = PropertyNameResolvers.CamelCase,
    Refiners = { new AdditionalPropertiesRefiner() },
};

JsonSchema jsonSchema = new JsonSchemaBuilder().FromType(type, config).AdditionalProperties(false).Build()
```

@gregsdennis It would've been nice to have this syntax to achieve the same result : 
```csharp
new JsonSchemaBuilder().FromType(type, config).AdditionalProperties(false, setOnChilds:true);
```

**Comment by margani** [comment] 2025-02-27 12:24
@epenelle-genetec Thank you, that is great.
