### ISSUE TITLE
Patch Path Not Escaping Forward Slash

### ISSUE THREAD

**Issue by treyhendon** [json-everything/json-everything#754] opened 2024-06-25 15:25 UTC
### Nuget Package

JsonPatch.Net

### Package Version

3.1.0

### Operating System

Linux

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

Beginning in 3.1.0 the patch is breaking when the target path has a forward slash (i.e. the Kubernetes annotation `kubectl.kubernetes.io/restartedAt`).  I was able to debug and print out the paths and value while debugging.

### v3.0.0.2 and prior
```
Path: /spec/template/metadata/annotations/kubectl.kubernetes.io~1restartedAt
Value: 
Path: /spec/template/metadata/annotations/date
Value: 1719328359
```

### v3.1.0
```
Path: /spec/template/metadata/annotations/kubectl.kubernetes.io/restartedAt
Value: 
Path: /spec/template/metadata/annotations/date
Value: 1719328538
```

### What did you expect?

Paths with forward slash should be escaped as prior versions.

### Please add test code or steps to reproduce the behavior.

https://github.com/RedSailTechnologies/kube-status/blob/3febdc3721dfc413d9c288c8a3063c374f4d3fd5/src/Data/DeploymentService.cs#L77

### Is there any other information you'd like to share regarding this bug?

Thank you for a great, simple tool!

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment] 2024-06-27 19:43
Hey there.  Thanks for the report.  I'll have a look.

**Comment by treyhendon** [comment] 2024-07-01 21:03
Sorry, was away for a few days.  Here's a simple console app that will show the differences in the path between 3.0.0.2 and 3.1.0.

```
using System.Text.Json;
using Json.Patch;

JsonDocument old = JsonDocument.Parse("{\"spec\":{\"replicas\":0,\"selector\":{\"matchLabels\":{\"app\":\"nginx\"}},\"template\":{\"metadata\":{\"creationTimestamp\":null,\"labels\":{\"app\":\"nginx\"},\"annotations\":{\"date\":\"1719861246\",\"kubectl.kubernetes.io/restartedAt\":\"123456\"}}}}}");
JsonDocument expected = JsonDocument.Parse("{\"spec\":{\"replicas\":0,\"selector\":{\"matchLabels\":{\"app\":\"nginx\"}},\"template\":{\"metadata\":{\"creationTimestamp\":null,\"labels\":{\"app\":\"nginx\"},\"annotations\":{\"date\":\"123456\",\"kubectl.kubernetes.io/restartedAt\":\"\"}}}}}");

var patch = old.CreatePatch(expected);

var patches = string.Empty;

foreach (var op in patch.Operations)
{
    patches += "Path: ";
    patches += op?.Path?.ToString() ?? "";
    patches += Environment.NewLine;
    patches += "Value: ";
    patches += op?.Value?.ToString() ?? "";
    patches += Environment.NewLine;
}

Console.WriteLine(patches);
```

**Comment by gregsdennis** [comment] 2024-07-01 21:22
@treyhendon Thanks, but that's not a test.  It's just a diff between two JSON objects.

I'm looking for a test method that I can add to my suite that fails because it replicates the undesired behavior.  Something like this:

https://github.com/json-everything/json-everything/blob/5b586a9735187a7a3134be1fc0f18b258b8ac7c3/src/JsonPatch.Tests/PatchExtensionTests.cs#L26-L52

**Comment by treyhendon** [comment] 2024-07-02 14:41
Sorry about that, how's this?

```
	[Test]
	public void CreatePatch3()
	{
		var initial = JsonDocument.Parse("{\"spec\":{\"replicas\":0,\"selector\":{\"matchLabels\":{\"app\":\"myapp\"}},\"template\":{\"metadata\":{\"creationTimestamp\":null,\"labels\":{\"app\":\"myapp\"},\"annotations\":{\"kubectl.kubernetes.io/restartedAt\":\"1719861246\",\"date\":\"1719861246\"}}}}}");
		var expected = JsonDocument.Parse("{\"spec\":{\"replicas\":0,\"selector\":{\"matchLabels\":{\"app\":\"myapp\"}},\"template\":{\"metadata\":{\"creationTimestamp\":null,\"labels\":{\"app\":\"myapp\"},\"annotations\":{\"kubectl.kubernetes.io/restartedAt\":\"\",\"date\":\"1719925004\"}}}}}");
		var patchExpected = JsonSerializer.Deserialize<JsonPatch>(
			"[{\"op\":\"replace\",\"path\":\"/spec/template/metadata/annotations/kubectl.kubernetes.io~1restartedAt\",\"value\":\"\"},{\"op\":\"replace\",\"path\":\"/spec/template/metadata/annotations/date\",\"value\":\"1719925004\"}]",
			TestEnvironment.SerializerOptions
		);

		var patch = initial.CreatePatch(expected, TestEnvironment.SerializerOptions);

		VerifyPatches(patchExpected!, patch);
	}
```

**Comment by gregsdennis** [comment] 2024-07-02 22:50
Looks like the problem is actually in _JsonPointer.Net_.

![image](https://github.com/json-everything/json-everything/assets/2676804/1a4464a1-7fea-41c7-b4a8-d2aa0f61b903)

**Comment by gregsdennis** [comment] 2024-07-02 23:30
The problem will be fixed in _JsonPointer.Net_, but I'm also pushing out updates to _JsonPatch.Net_ and _JsonSchema.Net_ which will use the fixed pointer package.

**Closed** 2024-07-02 23:33 UTC
Labels: bug, pkg:pointer
